name: Release new version

env:
  GO_VERSION: 1.21

permissions:
  contents: write

on:
  push:
    branches:
      - 'main'
      - 'dev/*/*/main'

jobs:
  prepare_changelog:
    name: prepare_changelog
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: version
        run: echo "version=$(bash ./workflow/version.sh $(go run ./workflow/version.go))" >> $GITHUB_OUTPUT
        id: version
      - name: changelog
        run: make changelog VERSION=$(go run ./workflow/version.go)
      - uses: actions/upload-artifact@v4
        with:
          name: release-changelog
          path: ./CURRENT-CHANGELOG.md
    outputs:
      version: ${{ steps.version.outputs.version }}
  publish_release:
    name: publish_release
    needs: prepare_changelog
    environment:
      name: app-release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: load-release-changelog
        uses: actions/download-artifact@v4
        with:
          name: release-changelog
          path: .
      - name: tag
        run: make release VERSION=${{ needs.prepare_changelog.outputs.version }}
      - name: release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          name: Release ${{ needs.prepare_changelog.outputs.version }}
          tag_name: ${{ needs.prepare_changelog.outputs.version }}
          body_path: ./CURRENT-CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}